title: SANTI SURYANI
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: uin
   url: /uin-suska.ac.id/

social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: santi.suryani@students.uin-suska.ac.id/
   sif: http://sif.uin-suska.ac.id/
   uin :http://uin-suska.ac.id/


google_analytics: "UA-58263416-1"
