title: SANTI SURYANI 
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://santisuryani.github.com/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
  url: /index.html
 - title: Contact
   url: /index.html
social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: shanty suryani
   email: santi.suryani@students.uin-suska.ac.id/
  


google_analytics: "UA-58263416-1"
