title: SANTI SURYANI 
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 -// title: sif
  // url: http://sif.uin-suska.ac.id/
 - //title: uin
   //url: http://uin-suska.ac.id/
// title: sif
  // url: http://sif.uin-suska.ac.id/
social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: shanty suryani
   email: santi.suryani@students.uin-suska.ac.id/
  


google_analytics: "UA-58263416-1"
