<body bg color="#000000"title: SANTI SURYANI 
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://santisuryani.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact
 - title: SIF UIN SUSKA
   url: //sif.uin-suska.ac.id/
 - title: UIN SUSKA RIAU
   url: //uin-suska.ac.id/
   
social:
   github: santisuryani
   twitter: brianmaierjr
   facebook: shanty suryani
   email: santi.suryani@students.uin-suska.ac.id/
  


google_analytics: "UA-58263416-1"

theme: jekyll-theme-cayman
